// import '@/modules/header/header-burger.module.js'
import '@/modules/search/search.module.js'
import '@/modules/city-change/city-change.module.js'
import '@/modules/calendar/calendar.module.js'
import '@/modules/promo-slider/promo-slider.module.js'
import '@/modules/ui-slider/ui-slider.module.js'
import '@/modules/rating/rating.module.js'
import '@/modules/auth-profile/auth-profile.module.js'
import '@/modules/actors-slider/actors-slider.module.js'
import '@/modules/reviews-slider/reviews-slider.module.js'
import '@/modules/modal-review/validation.js'
import '@/modules/top-users/top-users-aside.module.js'
import '@/modules/news/news-slider.js'
import '@/modules/modal-complaint/complaint-validation.js'
